// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/internal/dao/internal"
)

// codeGenTablesDao is the data access object for the table code_gen_tables.
// You can define custom methods on it to extend its functionality as needed.
type codeGenTablesDao struct {
	*internal.CodeGenTablesDao
}

var (
	// CodeGenTables is a globally accessible object for table code_gen_tables operations.
	CodeGenTables = codeGenTablesDao{internal.NewCodeGenTablesDao()}
)

// Add your custom methods and functionality below.
